version: '3.8'

services:
  app:
    build: .
    image: notion-db-manager
    container_name: notion-db-manager-app
    volumes:
      - ./src:/app/src
      - ./papers:/app/papers
    # command: python src/main.py
    command: bash -c "tail -f /dev/null"
    restart: always
    profiles:
      - app

  admin-app:
    build: .
    image: notion-db-manager-admin
    container_name: notion-db-manager-admin-app
    volumes:
      - ./src:/app/src
    command: bash -c "tail -f /dev/null"
    # command: python src/admin.py
    restart: always
    profiles:
      - admin-app